version = 0.1
[develop.deploy.parameters]
stack_name = "artograd-api"
resolve_s3 = true
s3_prefix = "artograd-api"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
