AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Artograd API Backend

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  ArogradAPI:
    Type: AWS::Serverless::Function
    Properties:
      #      AutoPublishAlias: bcn
      FunctionName: artograd-api-boot-3
      Handler: com.artograd.api.StreamLambdaHandler::handleRequest
      Runtime: java21
      SnapStart:
        ApplyOn: PublishedVersions
      CodeUri: .
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          MAIN_CLASS: com.artograd.api.Application
          AWS_COGNITO_USER_POOL_URI:
          ARTOGRAD_MONGO_DB_CONNECTION:
          AWS_COGNITO_USER_POOL_ID:
          CLOUDFRONT_DISTRIBUTION_DOMAIN:
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'

Outputs:
  SpringAtrogradApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: SpringArtogradApi