AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ArtogradApiSpringBootLambda
      Handler: com.artograd.api.StreamLambdaHandler::handleRequest
      Role: !ImportValue LambdaExecutionRoleArn
      Runtime: java21
      MemorySize: 512
      Timeout: 30
      SnapStart:
        ApplyOn: PublishedVersions
      Code:
        S3Bucket: artograd-api-s3-bucket
        S3Key: target/api-0.0.1-SNAPSHOT-lambda-package.zip
      Environment:
        Variables:
          MAIN_CLASS: com.artograd.api.Application