AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  FunctionName:
    Type: String
    Description: Lambda function name.

  DeploymentBucket:
    Type: String
    Description: The name of the S3 bucket that contains the application code.

  DeploymentKey:
    Type: String
    Description: The name of the .jar package in the S3 bucket.

  AwsCognitoUserPoolUriKey:
    Type: String
    Description: AWS_COGNITO_USER_POOL_URI value.

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: com.artograd.api.StreamLambdaHandler::handleRequest
      Role: !ImportValue LambdaExecutionRoleArn
      Runtime: java21
      MemorySize: 512
      Timeout: 30
      PackageType: Zip
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref DeploymentKey
      Environment:
        Variables:
          AWS_COGNITO_USER_POOL_URI: !Ref AwsCognitoUserPoolUriKey