AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ArtogradApiSpringBootLambda
      Handler: com.artograd.api.StreamLambdaHandler::handleRequest
      Role: !ImportValue LambdaExecutionRoleArn
      Runtime: java21
      MemorySize: 512
      Timeout: 30
      PackageType: Zip
      Code:
        S3Bucket: artograd-api-bucket
        S3Key: target/api-0.0.1-SNAPSHOT-lambda-package.zip
      Environment:
        Variables:
          AWS_COGNITO_USER_POOL_URI: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_YQqYTKSA2"